# Generated by Django 4.2 on 2023-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('Cpassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'details',
            },
        ),
    ]
