# Generated by Django 4.2 on 2023-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_address_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('dob', models.IntegerField()),
                ('work', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confpassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proffesional_details',
            },
        ),
    ]
