# Generated by Django 4.2.1 on 2023-05-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_servicesreq_alter_proffesional_dob_alter_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proffesional',
            name='confpassword',
        ),
        migrations.RemoveField(
            model_name='users',
            name='cpassword',
        ),
    ]
